# WARNING: NOT PARSED BY GITHUB YET!

name: Pull request
description: Create pull request for this project
labels: ["Type: Triage"]
assignees: self

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create a pull request!
        * Before creating a new pull request please check and search in [List of existing issues](https://github.com/Erriez/ErriezGithubActionsPlatformIODoxygen/issues?q=is%3Aissue) 
        * Please check [Online Documentation](https://github.com/Erriez/ErriezGithubActionsPlatformIODoxygen/blob/main/README.md)
        * Please provide specific title of the PR describing the change (eg: "Update PDF URL in Readme.md")
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your proposed Pull Request and it's impact.
      placeholder: This pull request fixes an issue with... and affects boards...
      render: plain
    validations:
      required: true
  
  - type: input
    id: issue
    attributes:
      label: Link to other issues
      description: Please provide relevant links to related issues, PRs etc.
      placeholder: eg "Issue #13"
    validations:
      required: true

  - type: input
    id: tested
    attributes:
      label: Tested version
      description: Which version did you use to test this pull request?
      placeholder: eg. "Branch main, hash 123456 or v1.0.0"
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Checks
      description: You agree to check all the resources above before opening a new pull request.
      options:
        - label: I confirm I have checked existing issues, online documentation and latest version when possible.
          required: true
      options:
        - label: I confirm I have tested this pull request. (Preferrably by running .auto-build.sh script)
          required: true
      options:
        - label: I confirm I have updated existing documentation (comments, Doxygen, README.md, Wiki).
          required: true
      options:
        - label: I understand that this library is maintained by volunteers in spare time. Response time may vary.
          required: true

  - type: checkboxes
    id: restrictions
    attributes:
      label: Export restrictions.
      description: The owner of this repository Erriez included an explict export restriction to Russia.
      options:
        - label: I accept [End User Agreement](https://github.com/Erriez/ErriezGithubActionsPlatformIODoxygen/blob/main/END_USER_AGREEMENT.md).
          required: true

  - type: markdown
    attributes:
      value: Thanks for your contribution!
